### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by spinatelli** [spinatelli/sebc#1]

**Comment by spinatelli** [comment]
Performed system checks and installed MySQL server on two nodes (Master and Slave Replica)

**Comment by spinatelli** [comment]
Installed Cloudera Manager service, started it and installed CDH on cluster

**Comment by spinatelli** [comment]
Added parcel repo, all documentation to MD files

**Comment by mfernest** [comment]
I'll evaluate the results this evening or if I have enough time during lab hours to concentrate on it.

**Comment by spinatelli** [comment]
@mfernest do you need the public IPs of the nodes? I would prefer not to put them in GitHub as they belong to a VPC created with my company's account.
